os:
- linux
sudo: required
language:
- python
python:
- 2.7
addons:
  apt:
    packages:
    - cmake
    - cmake-curses-gui
    - uuid-dev
    - libssl-dev
    - sasl2-bin
    - libsasl2-2
    - libsasl2-dev
    - sasl2-bin
    - swig
    - python-dev
    - ruby-dev
    - libperl-dev
    - git
    - make
    - valgrind

before_install:
- git submodule add https://github.com/apache/qpid-proton.git
- git submodule init
- git submodule update
before_script:
- cd qpid-proton
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=/usr
# This builds and installs qpid-proton
- sudo make install
- pushd proton-c/bindings/python/dist
- sudo python ./setup.py build install
- popd
- cd ../..
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=/usr
# This build qpid-dispatch
- sudo make install
script:
# Now run the unit tests
- ctest -VV
